### ISSUE TITLE
Read the docs footer and menu/hamburger is not clickable

### ISSUE THREAD

**Issue by davidbhr** [rgerum/saenopy#21]
On mobile devices or small windows the menu menu/hamburger is not clickable. Also the footer "v:latest" is not expandable.
This seems to be related to the "sphinx_rtd_theme":
https://github.com/readthedocs/readthedocs.org/issues/4132
https://github.com/readthedocs/readthedocs.org/issues/3925

However, when I build Readthedocs locally (with same versions of sphinx_rtd_theme), I do not encounter this problem.

Could it be related to the optional keyword here ? 
sphinx-rtd-theme = { version = "^1.1.1", optional = true }
nbsphinx = { version = "^0.8.10", optional = true }
sphinx-gallery = {version = "^0.11.1", optional = true }

**Comment by rgerum** [comment]
the optional is just that a user does not need these packages. They should be installed on readthedocs. Older docs worked. stange

**Comment by rgerum** [comment]
Hmm I have updated the readthedocs theme and sphinx and it still does not work. Apparently its a problem that "jQuery is not found" (in the javascript console F12). Sphinx 6 apparently removed jquery but rtd-theme is still discussing whether to remove it or not.

**Comment by rgerum** [comment]
I finally found the solution, its now fixed [3f7d589](https://github.com/rgerum/saenopy/commit/3f7d58911b0dfc557931344c746706c2c258b780)
